# -*- coding: utf-8 -*-
"""파이토치텐서2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhM_FTwpgQuA3EEQ-Z66w3FfKMhRHUCN
"""

import torch
from torch.autograd import Variable
x = Variable(torch.tensor([[2.]]), requires_grad = True)
print('x = ', x)
print('x.data = ', x.data)
print('x.grad = ', x.grad)
print('x.grad_fn() = ', x.grad_fn)
y = x * x * 3
print('\ny = ', y)
print('y.data = ', y.data)
print('y.grad = ', y.grad)
print('y.grad_fn() = ', y.grad_fn)
z = y**2
print('\nz = ', z)
print('z.data = ', z.data)
print('z.grad = ', z.grad)
z.backward( )
print('\nAfter invocation of backward()')
print('\nx = ', x)
print('x.data = ', x.data)
print('x.grad = ', x.grad)
print('x.grad_fn() = ', x.grad_fn)
print('\ny = ', y)
print('y.data = ', y.data)
print('y.grad = ', y.grad)
print('y.grad_fn() = ', y.grad_fn)
print('\nz = ', z)
print('z.data = ', z.data)
print('z.grad = ', z.grad)