# -*- coding: utf-8 -*-
"""encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HKOt-NPu1qrPWwSbUKRSyQEKLSHPvSiR
"""

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)

label_encoder = LabelEncoder() # 정수 인코딩
integer_encoded = label_encoder.fit_transform(values)
print('\n정수 인코딩 \n', integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False) # one-hot 인코딩
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print('\none-hot 인코딩 \n', onehot_encoded)

inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0,:])])
print('\n', onehot_encoded[0], '=> ', inverted)

