# -*- coding: utf-8 -*-
"""데이터 주석세트 생성.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z0GOhlgYFykNMAnGNNDoF547ubX5IAJf

# 킷 설치
"""

import sys
!{sys.executable} -m pip install -U deepposekit

import numpy as np
import cv2
import h5py
import matplotlib.pyplot as plt
from deepposekit.io import VideoReader, DataGenerator, initialize_dataset
from deepposekit.annotate import KMeansSampler
import tqdm
import glob
import pandas as pd

from os.path import expanduser

try:
    import google.colab
    IN_COLAB = True
except:
    IN_COLAB = False

HOME = expanduser("~") if not IN_COLAB else '.'

"""# 가능한 이미지 사이즈
반복적으로 2로 나눌 수 있는 이미지 해상도만 지원함 > CloudConvert 사용해서 사이즈 조정
"""

exp = np.arange(1,12)
exp = 2**exp

print(1*exp)
print(3*exp)
print(5*exp)
print(7*exp)
print(11*exp)

"""# 비디오 샘플링"""

reader = VideoReader('/content/drive/My Drive/Chromakey - 11342.mp4', batch_size=100, gray=True)

randomly_sampled_frames = []
for idx in tqdm.tqdm(range(len(reader)-1)):
    batch = reader[idx]
    random_sample = batch[np.random.choice(batch.shape[0], 10, replace=False)]
    randomly_sampled_frames.append(random_sample)
reader.close()

randomly_sampled_frames = np.concatenate(randomly_sampled_frames)
randomly_sampled_frames.shape

"""# K-means 알고리즘 적용
K-means 알고리즘을 적용하여 샘플링한 이미지를 KMeansSmapler 분포에 걸쳐 샘플링을 균등하게 하고 주석 세트 내에서 상관관계를 줄이는데 사용한다.
"""

kmeans = KMeansSampler(n_clusters=10, max_iter=1000, n_init=10, batch_size=100, verbose=True)
kmeans.fit(randomly_sampled_frames)

kmeans.plot_centers(n_rows=2)
plt.show()

kmeans_sampled_frames, kmeans_cluster_labels = kmeans.sample_data(randomly_sampled_frames, n_samples_per_label=10)
kmeans_sampled_frames.shape

"""# 스켈레톤 파일 정의
키포인트 이름, 상위 관계 및 양방향 대칭 부품에 대한 스왑 관계가 포함 된 .xlsx 또는 .csv 파일을 만들어야한다.  (반전 확대를 사용하는 경우에만 관련됨)  
parent및 swap열을 생략하면 데이터에 주석을 달고 모델을 학습하는 데 사용되지 않는다.
"""

