# -*- coding: utf-8 -*-
"""tensor_keras_MLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10vjvxtoNbkWmOM00bRYtUmr6NSYJ4Oxt
"""

import tensorflow as tf

# MNIST 데이터 가져오기
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 입력 데이터 졍규화
x_train, x_test = x_train/255.0, x_test/255.0

# 신경망 모델 구성
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

# 학습을 위한 optimizer와 손실함수 선택
model.compile(optimizer = 'adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 학습 데이터를 이용한 모델 학습, 5회 반복
model.fit(x_train, y_train, epochs=5)

# 테스트 데이터를 이용한 모델 평가
model.evaluate(x_test, y_test)

