# -*- coding: utf-8 -*-
"""tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VcEn6BOjR4sg_A4bQT4XHTfLQAl-kihw
"""

import tensorflow as tf

tensor_a = tf.constant('hello world')
print(tensor_a)
print(tensor_a.numpy())
print(tensor_a.numpy().decode('utf-8'))
tensor_b = tf.constant('안녕')
print(tensor_b)
print(tensor_b.numpy())
print(tensor_b.numpy().decode('utf-8'))

a=tf.constant(10)
b=tf.constant(8)
print(a.numpy())
c=tf.multiply(a,b) # 실수 곱셈
print('c =', c)
d=a+b
print('d =', d)

A=tf.constant([[1,2],[3,4]])
print('A = ',A)
B=tf.constant([[2,0],[0,2]])
print('B = ', B)
C=tf.matmul(A,B) # 행렬 곱셈
print('C = ', C.numpy())

